// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package nodejs

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
)

const autogeneratedMarker = "This file is automatically generated by gapic-generator-typescript."

var (
	// Files to delete without any checking, relative to the package directory.
	simpleFilesToClean = []string{
		"protos/protos.d.ts",
		"protos/protos.js",
		"protos/protos.json",
		"samples/package.json",
		"package.json",
		"tsconfig.json",
		"webpack.config.js",
		".eslintignore",
		".gitignore",
		".nycrc",
		"README.md",
		".OwlBot.yaml",
	}
	sourceDirectoriesToClean = []string{
		"samples",
		"src",
		"system-test",
		"test",
	}
)

// Clean removes all generated code from beneath the given library's
// output directory. If the output directory does not currently exist, this
// function is a no-op.
func Clean(lib *config.Library) error {
	_, err := os.Stat(lib.Output)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	if err := cleanFiles(lib, "protos", ".proto", ""); err != nil {
		return err
	}
	if err := cleanFiles(lib, "src", ".json", ""); err != nil {
		return err
	}
	for _, sourceDirectory := range sourceDirectoriesToClean {
		if err := cleanFiles(lib, sourceDirectory, ".js", autogeneratedMarker); err != nil {
			return err
		}
		if err := cleanFiles(lib, sourceDirectory, ".ts", autogeneratedMarker); err != nil {
			return err
		}
	}
	// FIXME: Observe the keep list... (I suspect we'll need this for oddities).
	for _, file := range simpleFilesToClean {
		if err := os.Remove(filepath.Join(lib.Output, file)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}

func cleanFiles(lib *config.Library, subDir, suffix, marker string) error {
	return filepath.WalkDir(filepath.Join(lib.Output, subDir), func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), suffix) {
			return nil
		}
		if marker != "" {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !strings.Contains(string(content), marker) {
				return nil
			}
		}
		// FIXME: Observe the keep list... (I suspect we'll need this for oddities).
		return os.Remove(path)
	})
}
