// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package nodejs

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
)

const autogeneratedMarker = "This file is automatically generated by gapic-generator-typescript."

var (
	// Files to delete without any checking, relative to the package directory.
	simpleFilesToClean = []string{
		"protos/protos.d.ts",
		"protos/protos.js",
		"protos/protos.json",
		"samples/package.json",
		"package.json",
		"tsconfig.json",
		"webpack.config.js",
		".eslintignore",
		".gitignore",
		".nycrc",
		"README.md",
		".OwlBot.yaml",
	}
)

// Clean removes all generated code from beneath the given library's
// output directory. If the output directory does not currently exist, this
// function is a no-op.
func Clean(lib *config.Library) error {
	_, err := os.Stat(lib.Output)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}

	keepSet, err := buildKeepSet(lib.Output, lib.Keep)
	if err != nil {
		return err
	}

	if err := cleanFiles(lib, keepSet, "protos", "", ""); err != nil {
		return err
	}
	if err := cleanFiles(lib, keepSet, "src", "", ""); err != nil {
		return err
	}
	if err := cleanFiles(lib, keepSet, filepath.Join("samples", "generated"), "", ""); err != nil {
		return err
	}

	// For test and system-test, we only clean .js and .ts files that have the autogeneratedMarker
	for _, sourceDirectory := range []string{"test", "system-test"} {
		if err := cleanFiles(lib, keepSet, sourceDirectory, ".js", autogeneratedMarker); err != nil {
			return err
		}
		if err := cleanFiles(lib, keepSet, sourceDirectory, ".ts", autogeneratedMarker); err != nil {
			return err
		}
	}

	for _, file := range simpleFilesToClean {
		if isKept(keepSet, file) {
			continue
		}
		if err := os.Remove(filepath.Join(lib.Output, file)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}

func buildKeepSet(dir string, keep []string) (map[string]bool, error) {
	info, err := os.Stat(dir)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, nil
		}
		return nil, fmt.Errorf("cannot access output directory %q: %w", dir, err)
	}
	if !info.IsDir() {
		return nil, fmt.Errorf("%q is not a directory", dir)
	}
	keepSet := make(map[string]bool)
	for _, k := range keep {
		path := filepath.Join(dir, k)
		if _, err := os.Stat(path); errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("error keeping %s: %w", k, err)
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return nil, err
		}
		keepSet[rel] = true
	}
	return keepSet, nil
}

func cleanFiles(lib *config.Library, keepSet map[string]bool, subDir, suffix, marker string) error {
	err := filepath.WalkDir(filepath.Join(lib.Output, subDir), func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		relPath, err := filepath.Rel(lib.Output, path)
		if err != nil {
			return err
		}
		if isKept(keepSet, relPath) {
			return nil
		}
		if suffix != "" && !strings.HasSuffix(d.Name(), suffix) {
			return nil
		}
		if marker != "" {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !strings.Contains(string(content), marker) {
				return nil
			}
		}
		return os.Remove(path)
	})
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	return err
}

func isKept(keepSet map[string]bool, relPath string) bool {
	for p := relPath; p != "." && p != "/"; p = filepath.Dir(p) {
		if keepSet[p] {
			return true
		}
	}
	return false
}
