// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

// Command represents the top-level structure for a gcloud command definition.
// TODO(coryan): // This struct is designed to be marshaled into a YAML file that the gcloud generator can
type Command struct {
	// ReleaseTracks specifies the release tracks (e.g., GA, BETA, ALPHA) for which
	// this command is available.
	// Origin: Derived from the `release_tracks` field in the `gcloud.yaml` config file.
	    ReleaseTracks []string `yaml:"release_tracks,omitempty"`
	    // TODO(julieqiu): Put line breaks in between these for readability (and same below)
	    AutoGenerated bool `yaml:"auto_generated,omitempty"`	// Hidden specifies whether this command should be hidden from the user in
	// help text and command listings.
	// Origin: Hardcoded to `true` by this generator.
	Hidden bool `yaml:"hidden,omitempty"`
	// HelpText contains the brief and detailed help text for the command.
	// Origin: Populated from `method_rules` in the `gcloud.yaml` config file.
	HelpText HelpText `yaml:"help_text,omitempty"`
	// Arguments defines the set of flags and positional arguments for the command.
	// Origin: Generated by parsing the fields of the method's request message from the proto.
	Arguments Arguments `yaml:"arguments,omitempty"`
	// Request specifies the details of the API request to be made when the
	// command is executed.
	// Origin: Generated by `newRequest`, which determines the API version and collection.
	Request *Request `yaml:"request,omitempty"`
	// Async specifies the configuration for handling long-running operations.
	// Origin: Generated by `newAsync` if the proto method is annotated as a long-running operation.
	Async *Async `yaml:"async,omitempty"`
}

// HelpText holds the brief and detailed help text for the command.
// It maps to the `help_text` section of the gcloud YAML schema.
type HelpText struct {
	// Brief is a short, one-line summary of what the command does.
	// Origin: From the `brief` field in a `method_rule` in `gcloud.yaml`.
	Brief string `yaml:"brief,omitempty"`
	// Description is a more detailed explanation of the command's functionality.
	// Origin: From the `description` field in a `method_rule` in `gcloud.yaml`.
	Description string `yaml:"description,omitempty"`
	// Examples provides one or more examples of how to use the command.
	// Origin: From the `examples` field in a `method_rule` in `gcloud.yaml`.
	Examples string `yaml:"examples,omitempty"`
}

// Arguments contains the list of parameters (flags and positionals) for the command.
// It maps to the `arguments` section of the gcloud YAML schema.
type Arguments struct {
	// Params is a slice of Param structs, each defining a single argument.
	// Origin: Generated by iterating over the fields of a method's request message.
	Params []Param `yaml:"params,omitempty"`
}

// Param represents a single command-line argument or flag.
// It maps to an item in the `arguments.params` list in the gcloud YAML schema.
type Param struct {
	// ArgName is the name of the argument as it appears on the command line
	// (e.g., "instance-id").
	// Origin: Derived from the proto field name, converted to kebab-case.
	ArgName string `yaml:"arg_name,omitempty"`
	// APIField is the dot-separated path to the field in the API request message
	// that this argument's value should be placed in (e.g., "instance.name").
	// Origin: Derived from the `json_name` of the proto field, with prefixes for nested messages.
	APIField string `yaml:"api_field,omitempty"`
	// HelpText is the help text for this specific argument.
	// Origin: From a `field_rule` in `gcloud.yaml`, or a default value is generated if none is provided.
	HelpText string `yaml:"help_text"`
	// IsPositional indicates that this argument is a positional argument rather
	// than a flag.
	// Origin: Set to `true` for the primary resource argument of a command.
	IsPositional bool `yaml:"is_positional,omitempty"`
	// IsPrimaryResource indicates that this argument represents the primary
	// resource being acted upon by the command.
	// Origin: Set to `true` for the primary resource argument, identified by its field name (e.g., "name").
	IsPrimaryResource bool `yaml:"is_primary_resource,omitempty"`
	// RequestIDField is the name of the field in the request message that should
	// hold the ID of the resource being created. This is used for `Create` methods.
	// Origin: Derived from the name of the primary resource's ID field (e.g., "instance_id").
	RequestIDField string `yaml:"request_id_field,omitempty"`
	// ResourceSpec defines the structure of a resource argument, including its
	// name, collection, and attributes.
	// Origin: Generated for fields that have a `(google.api.resource_reference)` annotation.
	ResourceSpec *ResourceSpec `yaml:"resource_spec,omitempty"`
	// Required indicates that this argument must be provided by the user.
	// Origin: Inferred from the `(google.api.field_behavior) = REQUIRED` annotation on the proto field.
	Required bool `yaml:"required"`
	// Repeated indicates that this argument can be specified multiple times.
	// Origin: Inferred from the `repeated` keyword on the proto field.
	Repeated bool `yaml:"repeated"`
	// Type specifies the data type of the argument's value (e.g., "long", "float").
	// Origin: Mapped from the proto field's data type (e.g., `int64` becomes `long`).
	Type string `yaml:"type,omitempty"`
	// Choices is a list of valid values for an enum-based argument.
	// Origin: Generated by iterating over the values of a proto `enum`.
	Choices []Choice `yaml:"choices,omitempty"`
	// Spec defines the structure for complex argument types, such as key-value pairs for a map.
	// Origin: Generated for `map` fields in a proto message.
	Spec []ArgSpec `yaml:"spec,omitempty"`
	// ResourceMethodParams maps API method parameters to resource attributes,
	// used for non-standard resource name formats.
	// Origin: Generated for resource reference arguments to map the parsed name correctly.
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

// ArgSpec defines the structure within a complex argument type, such as the
// key and value fields for a map.
type ArgSpec struct {
	// APIField is the name of the field in the API message (e.g., "key", "value").
	// Origin: Hardcoded to "key" and "value" for map fields.
	APIField string `yaml:"api_field,omitempty"`
}

// Choice represents a single option for an enum-based argument.
// It maps to an item in the `choices` list for a parameter.
type Choice struct {
	// ArgValue is the value as it appears on the command line (e.g., "balanced").
	// Origin: Derived from the proto enum value name, converted to kebab-case.
	ArgValue string `yaml:"arg_value,omitempty"`
	// EnumValue is the corresponding string value of the enum in the API.
	// Origin: The original name of the value in the proto enum definition.
	EnumValue string `yaml:"enum_value,omitempty"`
}

// ResourceSpec defines the structure for a gcloud resource argument. It provides
// gcloud with the information it needs to parse and handle resource names, and
// it maps to the `resource_spec` section in the gcloud YAML schema.
type ResourceSpec struct {
	// Name is the singular name of the resource (e.g., "instance").
	// Origin: Inferred from the last variable segment of a resource pattern (e.g., `{instance}`).
	Name string `yaml:"name,omitempty"`
	// PluralName is the plural name of the resource (e.g., "instances").
	// Origin: Derived from the `plural` field in the `(google.api.resource)` annotation, or
	// inferred from the literal segment preceding the final variable in the resource pattern.
	PluralName string `yaml:"plural_name,omitempty"`
	// Collection is the unique identifier for the resource type in gcloud's
	// resource registry (e.g., "parallelstore.projects.locations.instances").
	// Origin: Constructed from the API's service name and the literal collection identifiers
	// in the resource's pattern string, as defined by AIP-122.
	Collection string `yaml:"collection,omitempty"`
	// Attributes defines the components that make up a resource's unique name.
	// Origin: Generated by parsing the variable segments (e.g., `{project}`, `{location}`)
	// from the resource's pattern string.
	Attributes []Attribute `yaml:"attributes,omitempty"`
	// DisableAutoCompleters prevents gcloud from attempting to provide tab-completion
	// for this resource.
	// Origin: Hardcoded to `true` for referenced resources to avoid cross-API complexities.
	DisableAutoCompleters bool `yaml:"disable_auto_completers"`
}

// Attribute defines a single component of a resource's identifier, such as a
// project ID or a location. It maps to an item in the `attributes` list of a `resource_spec`.
type Attribute struct {
	// ParameterName is the name of the API field in the request path that this
	// attribute maps to (e.g., "projectsId").
	// Origin: Inferred from the literal collection identifier that precedes the variable
	// in the resource pattern (e.g., `projects/{project}` -> `projectsId`).
	ParameterName string `yaml:"parameter_name,omitempty"`
	// AttributeName is the name used for the gcloud flag for this attribute
	// (e.g., "project").
	// Origin: Inferred from the name of the variable in the resource pattern (e.g., `{project}`).
	AttributeName string `yaml:"attribute_name,omitempty"`
	// Help is the help text for the gcloud flag for this attribute.
	// Origin: Auto-generated using a standard template.
	Help string `yaml:"help,omitempty"`
	// Property is a gcloud core property that can be used as a fallback value
	// if the flag is not provided (e.g., "core/project").
	// Origin: Hardcoded for standard, well-known attributes like "project".
	Property string `yaml:"property,omitempty"`
}

// Request defines the API request details for the command.
// It maps to the `request` section of the gcloud YAML schema.
type Request struct {
	// APIVersion is the version of the API to call (e.g., "v1").
	// Origin: Derived from the `api_version` field in the `gcloud.yaml` config file.
	APIVersion string `yaml:"api_version,omitempty"`
	// Collection is the list of API collections that this command operates on.
	// Origin: Constructed from the API service name and the resource's collection path.
	Collection []string `yaml:"collection,omitempty"`
}

// Async defines the details for handling long-running operations.
// It maps to the `async` section of the gcloud YAML schema.
type Async struct {
	// Collection is the API collection for the long-running operation resource.
	// Origin: Hardcoded to the standard operations collection for the service.
	Collection []string `yaml:"collection,omitempty"`
}
